'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {fixture}=require('./humanClientAdmissionFixtures');
const C=require('../modules/humanClientAdmissionCrypto');
const {LIMITS,HumanClientAdmission}=require('../modules/humanClientAdmission');
const {ApprovalReceiptAuthority}=require('../modules/approvalReceiptAuthority');
const {ApprovalProtocol}=require('../modules/approvalProtocol');
function reject(fn,code){assert.throws(fn,code?{code}:undefined);}
for(const mutate of [x=>x+'=',x=>x+'A',x=>' '+x,x=>x.replace(/.$/,'!'),x=>Buffer.concat([Buffer.from(x,'base64url'),Buffer.from([0])]).toString('base64url')])test('crypto: strict SPKI '+mutate,()=>{const h=fixture();reject(()=>C.publicKey(mutate(h.publicKeySpki)));});
test('crypto: canonical Ed25519 SPKI, wrong key type and transcript verification',()=>{const h=fixture(),k=C.publicKey(h.publicKeySpki);assert.equal(k.fingerprint,C.hash(Buffer.from(h.publicKeySpki,'base64url')));const rsa=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});reject(()=>C.publicKey(rsa.publicKey.export({format:'der',type:'spki'}).toString('base64url')));const e=h.begin();assert.equal(h.a.counts().sessions,0);assert(C.verify(k.key,Buffer.from(e.proof.signingInput,'base64url'),h.sign(e.proof).signature));});
for(const tweak of [s=>s+'=',s=>'!'+s,s=>s.slice(1),s=>Buffer.alloc(63).toString('base64url')])test('crypto: strict signature '+tweak,()=>{const h=fixture(),e=h.begin();h.a.browserDecision(e.enrollmentId,'approve');const p=h.sign(e.proof);p.signature=tweak(p.signature);reject(()=>h.a.claim(e.enrollmentId,p),'PROOF_INVALID');assert.equal(h.a.counts().sessions,0);});
for(const state of ['unapproved','denied','expired','wrong-key'])test('enrollment: reject '+state,()=>{const h=fixture(),e=h.begin();if(state==='denied')h.a.browserDecision(e.enrollmentId,'deny');if(state==='expired')h.advance(LIMITS.enrollmentMs);if(state==='wrong-key')h.a.browserDecision(e.enrollmentId,'approve');const key=state==='wrong-key'?crypto.generateKeyPairSync('ed25519').privateKey:h.keys.privateKey;reject(()=>h.a.claim(e.enrollmentId,h.sign(e.proof,key)));assert.equal(h.a.counts().sessions,0);});
test('enrollment: explicit approved waiting proof, one claim, safe public status',()=>{const h=fixture(),e=h.begin();assert.equal(e.state,'PENDING_HUMAN');h.a.browserDecision(e.enrollmentId,'approve');assert.equal(h.a.enrollment(e.enrollmentId).state,'APPROVED_WAITING_PROOF');assert.equal(h.a.counts().sessions,0);const s=h.a.claim(e.enrollmentId,h.sign(e.proof));assert.equal(s.sessionState,'AUTHENTICATED');assert.equal(s.expiresAt-s.createdAt,LIMITS.sessionMs);reject(()=>h.a.claim(e.enrollmentId,h.sign(e.proof)));assert.equal(h.a.counts().sessions,1);assert(!JSON.stringify(h.a.list()).includes('signingInput'));assert(!JSON.stringify(h.a.list()).includes('private'));});
for(const [field,val]of [['surface','vcp_mobile'],['hostBootId','other'],['trustedHostOrigin','https://other.fixture'],['path','/other'],['nonceId','other'],['purpose','self-revoke'],['method','GET']])test('proof: modified signed '+field,()=>{const h=fixture(),s=h.enroll(),p=h.a.nonce(s.sessionId,'capability-mint');const fake=C.transcript({...p.boundFields,[field]:val});const bad={nonceId:p.nonceId,signature:crypto.sign(null,fake.bytes,h.keys.privateKey).toString('base64url')};reject(()=>h.a.mint(s.sessionId,bad),'PROOF_INVALID');const c=h.a.mint(s.sessionId,h.sign(p));assert(c.capability);reject(()=>h.a.mint(s.sessionId,h.sign(p)),'PROOF_REPLAYED');});
test('proof: wrong owner, wrong purpose, expired, copied ID, restart all fail',()=>{const h=fixture(),s=h.enroll(),s2=h.enroll(),p=h.a.nonce(s.sessionId,'self-revoke');reject(()=>h.a.mint(s.sessionId,h.sign(p)));reject(()=>h.a.selfRevoke(s2.sessionId,h.sign(p)));h.advance(LIMITS.nonceMs);reject(()=>h.a.selfRevoke(s.sessionId,h.sign(p)),'PROOF_EXPIRED');reject(()=>h.a.mint(s.sessionId,{nonceId:'unknown',signature:'x'}));const restart=fixture();reject(()=>restart.a.selfRevoke(s.sessionId,h.sign(p)),'SESSION_UNKNOWN');});
for(const field of ['clientSurface','deviceName','VCP_Key','USER_AUTH_CODE','tool_password','clientId','serverId','session_id'])test('spoofing: enrollment rejects '+field,()=>{const h=fixture();reject(()=>h.a.begin({protocolVersion:1,publicKeySpki:h.publicKeySpki,[field]:'vcp_mobile'},'fixture'));assert.equal(h.a.counts().sessions,0);});
test('spoofing: no generic surface/nonce/pseudo lease admission',()=>{const h=fixture(),s=h.enroll();reject(()=>h.a.nonce(s.sessionId,'vcp_mobile'),'SURFACE_NOT_ADMITTED');reject(()=>h.authority.issueClientChannel({...s,surface:'vcp_chat'}));assert.equal(h.authority.isHuman({sessionId:s.sessionId,human:true,clientSurface:'vcp_chat'}),false);});
test('capability: exact proof gives one-use same core cap, cross-route Admin rejected',()=>{const h=fixture(),s=h.enroll(),c=h.cap(s);assert.equal(Buffer.from(c.capability,'base64url').length,32);reject(()=>h.authority.claimChannel(c.capability));const cl=h.authority.claimClientChannel(c.capability);assert.equal(cl.clientSurface,'vcp_chat');reject(()=>h.authority.claimClientChannel(c.capability));const admin=h.authority.issueChannel({headers:{authorization:h.auth}},h.env);reject(()=>h.authority.claimClientChannel(admin));h.authority.claimChannel(admin);});
test('websocket: capability only not human, exact proof binds once to exact socket',()=>{const h=fixture(),s=h.enroll(),cl=h.authority.claimClientChannel(h.cap(s).capability),ws=h.socket(),p=h.a.beginChannel(ws,cl);assert(!h.authority.isHuman(ws));reject(()=>h.authority.bindClientChannel(ws,cl));reject(()=>h.a.completeChannel(h.socket(),h.sign(p)));reject(()=>h.a.completeChannel(ws,h.sign(p,crypto.generateKeyPairSync('ed25519').privateKey)));h.a.completeChannel(ws,h.sign(p));assert(!h.authority.isHuman(ws));assert.equal(h.authority.humanContext(ws),null);assert.equal(h.a.client(s.clientEnrollmentId).productionAdmission,'DENIED');reject(()=>h.a.completeChannel(ws,h.sign(p)));ws.close();});
for(const phase of ['capability','claimed','pending','trusted'])test('revocation: lease recheck at '+phase,()=>{const h=fixture(),s=h.enroll(),cap=h.cap(s).capability;let claim,ws,p;if(phase!=='capability')claim=h.authority.claimClientChannel(cap);if(['pending','trusted'].includes(phase)){ws=h.socket();p=h.a.beginChannel(ws,claim);}if(phase==='trusted')h.a.completeChannel(ws,h.sign(p));h.a.revoke(s.sessionId);if(phase==='capability')reject(()=>h.authority.claimClientChannel(cap));if(phase==='claimed')reject(()=>h.a.beginChannel(h.socket(),claim));if(phase==='pending')reject(()=>h.a.completeChannel(ws,h.sign(p)));if(ws){assert(!h.authority.isHuman(ws));assert(ws.closed);}reject(()=>h.cap(s),'SESSION_REVOKED');});
test('revocation: self proof exact, wrong key and replay rejected, unrelated lease unaffected',()=>{const h=fixture(),s=h.enroll(),s2=h.enroll(),p=h.a.nonce(s.sessionId,'self-revoke');reject(()=>h.a.selfRevoke(s.sessionId,h.sign(p,crypto.generateKeyPairSync('ed25519').privateKey)));h.a.selfRevoke(s.sessionId,h.sign(p));reject(()=>h.a.selfRevoke(s.sessionId,h.sign(p)));assert.equal(h.a.list().find(x=>x.sessionId===s2.sessionId).sessionState,'AUTHENTICATED');});
test('expiry: exact boundary rejects nonce, cap claim, pending proof and human status without timers',()=>{const h=fixture(),s=h.enroll(),ws=h.channel(s);h.advance(LIMITS.sessionMs-1);const c=h.cap(s).capability;h.advance(1);assert(!h.authority.isHuman(ws));assert.equal(h.authority.humanContext(ws),null);reject(()=>h.authority.claimClientChannel(c));reject(()=>h.a.nonce(s.sessionId,'self-revoke'));h.a.sweep();assert(ws.closed);assert.equal(h.a.counts().sessions,0);});
test('expiry: cap and upgrade deadlines are separately enforced',()=>{const h=fixture(),s=h.enroll(),c=h.cap(s).capability;h.advance(60000);reject(()=>h.authority.claimClientChannel(c));const cl=h.authority.claimClientChannel(h.cap(s).capability),ws=h.socket(),p=h.a.beginChannel(ws,cl);h.advance(LIMITS.upgradeMs);reject(()=>h.a.completeChannel(ws,h.sign(p)));assert(!h.authority.isHuman(ws));ws.close();});
function adminSocket(h){const ws=h.socket();h.authority.bindChannel(ws,h.authority.claimChannel(h.authority.issueChannel({headers:{authorization:h.auth}},h.env)));return ws;}
function receipt(h,ws){const args={command:'grant',requestId:'fixture-public',projectRoot:'/fixture/not-executed',purpose:'propose'};const record=h.authority.snapshot('CodexWorker',args,{requiresApproval:true,matchedRule:'CodexWorker:grant',matchedCommand:'grant'},{});const handle=h.authority.approve(record,'fixture-host',ws);return {args,handle,expected:{toolName:'CodexWorker',command:'grant',requestId:args.requestId,payload:args}};}
for(const phase of ['unbound','bound','consumed','expired'])test('receipt_races: '+phase,()=>{const h=fixture(),s=h.enroll(),ws=h.channel(s),r=receipt(h,adminSocket(h)),ctx={};if(phase!=='unbound')h.authority.bindInvocation(r.handle,ctx,r.args);if(phase==='consumed')h.authority.verifyAuthorization(r.expected,ctx);if(phase==='expired')h.advance(LIMITS.sessionMs);else h.a.revoke(s.sessionId);if(phase==='unbound'){h.authority.bindInvocation(r.handle,ctx,r.args);assert(h.authority.verifyAuthorization(r.expected,ctx).authorityGateVerified);}else if(phase==='consumed'){assert.equal(h.authority.invocationAudit(ctx).state,'CONSUMED');reject(()=>h.authority.verifyAuthorization(r.expected,ctx));assert.equal(h.authority.invocationAudit(ctx).state,'CONSUMED');}else if(phase==='expired')reject(()=>h.authority.verifyAuthorization(r.expected,ctx));else assert(h.authority.verifyAuthorization(r.expected,ctx).authorityGateVerified);ws.close();});
test('receipt_races: accepted terminal remains ALLOWED after revoke before verification; sync rejects revoked connection',async()=>{const h=fixture(),s=h.enroll(),ws=h.channel(s);const args={command:'grant',requestId:'fake-public',projectRoot:'/fake',purpose:'propose'};const record=h.authority.snapshot('CodexWorker',args,{requiresApproval:true,matchedRule:'CodexWorker:grant',matchedCommand:'grant'},{});const p=new ApprovalProtocol({authority:h.authority});const x=p.create({requestId:'fake-host',toolName:'CodexWorker',args,sensitiveApproval:record,timeoutMs:1000});assert.equal(p.respond({requestId:'fake-host',approved:true},adminSocket(h)).outcome,'ACCEPTED');const handle=await x.promise;h.a.revoke(s.sessionId);h.authority.bindInvocation(handle,{},args);assert.equal(p.inspect('fake-host').terminalState,'ALLOWED');assert.equal(p.sync(ws).outcome,'CLIENT_NOT_AUTHORIZED');});
test('existing_admin: no key proof, source class and receipt verification remain compatible',()=>{const h=fixture(),ws=h.socket();h.authority.bindChannel(ws,h.authority.claimChannel(h.authority.issueChannel({headers:{authorization:h.auth}},h.env)));assert.equal(h.authority.humanContext(ws).sourceClass,'authenticated_admin_session');const r=receipt(h,ws),ctx={};h.authority.bindInvocation(r.handle,ctx,r.args);assert(h.authority.verifyAuthorization(r.expected,ctx).authorityGateVerified);ws.close();});
test('capacity: per-source rate and key-before-allocation',()=>{const h=fixture();for(let i=0;i<20;i++)reject(()=>h.a.begin({protocolVersion:1,publicKeySpki:'bad'},'bad'));assert.equal(h.a.counts().enrollments,0);for(let i=0;i<LIMITS.startsPerMinute;i++)h.a.begin({protocolVersion:1,publicKeySpki:h.publicKeySpki},'same');reject(()=>h.a.begin({protocolVersion:1,publicKeySpki:h.publicKeySpki},'same'),'CAPACITY_REACHED');});
test('capacity: enrollment hard bound and expiry cleanup',()=>{const h=fixture();for(let i=0;i<LIMITS.enrollments;i++)h.begin();const c=h.a.counts();reject(()=>h.begin(),'CAPACITY_REACHED');assert.equal(h.a.counts().enrollments,c.enrollments);h.advance(LIMITS.enrollmentMs);assert.equal(h.a.counts().enrollments,0);assert(h.begin());});
test('capacity: sessions bounded; durable identities persist while expired sessions free slots',()=>{const h=fixture();let existing;for(let i=0;i<LIMITS.sessions;i++)existing=h.enroll();const e=h.begin();h.a.browserDecision(e.enrollmentId,'approve');reject(()=>h.a.claim(e.enrollmentId,h.sign(e.proof)),'CAPACITY_REACHED');assert.equal(h.a.enrollment(e.enrollmentId).state,'APPROVED_WAITING_PROOF');h.advance(LIMITS.sessionMs);assert.equal(h.a.counts().sessions,0);assert.equal(h.store.snapshot().clients.length,256);const p=h.a.sessionChallenge(existing.clientEnrollmentId);assert(h.a.authenticate(existing.clientEnrollmentId,h.sign(p)));const extra=h.begin();h.a.browserDecision(extra.enrollmentId,'approve');reject(()=>h.a.claim(extra.enrollmentId,h.sign(extra.proof)),'CAPACITY_REACHED');});
test('capacity: per-session/global nonce bounds and cleanup',()=>{const h=fixture();for(let j=0;j<LIMITS.nonces/LIMITS.perSessionNonces;j++){const s=h.enroll();for(let i=0;i<LIMITS.perSessionNonces;i++)h.a.nonce(s.sessionId,'capability-mint');reject(()=>h.a.nonce(s.sessionId,'capability-mint'),'CAPACITY_REACHED');}assert.equal(h.a.counts().nonces,LIMITS.nonces);reject(()=>h.begin(),'CAPACITY_REACHED');h.advance(LIMITS.nonceMs);assert.equal(h.a.counts().nonces,0);});
test('capacity: pending and trusted sockets share limit; close frees slot',()=>{const h=fixture(),s=h.enroll(),sockets=[];for(let i=0;i<LIMITS.sockets;i++){const ws=h.socket();h.a.beginChannel(ws,h.authority.claimClientChannel(h.cap(s).capability));sockets.push(ws);}reject(()=>h.a.beginChannel(h.socket(),h.authority.claimClientChannel(h.cap(s).capability)),'CAPACITY_REACHED');sockets[0].close();const ws=h.channel(s);assert(!h.authority.isHuman(ws));for(const x of sockets)x.close();ws.close();assert.equal(h.a.counts().sockets,0);});
test('capacity: CSRF and bounded enrollment terminal history',()=>{const h=fixture();for(let i=0;i<LIMITS.csrf;i++)h.a.csrf('principal','resource'+i);reject(()=>h.a.csrf('principal','more'),'CAPACITY_REACHED');h.advance(LIMITS.csrfMs);assert(h.a.csrf('principal','new'));for(let i=0;i<LIMITS.terminal+5;i++){const e=h.begin();h.a.browserDecision(e.enrollmentId,'deny');}assert.equal(h.a.counts().terminal,LIMITS.terminal);});
test('origin: explicit canonical HTTPS origins only; no header-derived fallback',()=>{for(const x of ['',undefined,'http://host.fixture','https://host.fixture/','https://u:p@host.fixture','https://HOST.fixture','https://host.fixture:443'])reject(()=>new HumanClientAdmission({authority:new ApprovalReceiptAuthority(),trustedHostOrigin:x,trustedAdminOrigin:'https://admin.fixture'}),'ADMISSION_DISABLED');});
test('receipt_races: cleanup does not rewrite consumed or invalidated history',()=>{const h=fixture(),s=h.enroll(),ws=h.channel(s),r=receipt(h,adminSocket(h)),ctx={};h.authority.bindInvocation(r.handle,ctx,r.args);h.authority.verifyAuthorization(r.expected,ctx);h.a.revoke(s.sessionId);h.advance(60000);h.authority.assertClientCapacity();assert.equal(h.authority.invocationAudit(ctx).state,'CONSUMED');reject(()=>h.authority.bindInvocation(r.handle,{},r.args));assert.equal(h.authority.invocationAudit(ctx).state,'CONSUMED');});
test('receipt_races: session expires before fresh receipt TTL; receipt remains consumable',()=>{const h=fixture(),s=h.enroll();h.advance(LIMITS.sessionMs-1);const ws=h.channel(s),r=receipt(h,adminSocket(h)),ctx={};h.authority.bindInvocation(r.handle,ctx,r.args);h.advance(1);assert(h.authority.verifyAuthorization(r.expected,ctx).authorityGateVerified);assert.equal(h.authority.invocationAudit(ctx).state,'CONSUMED');ws.close();});
