'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const C=require('../modules/humanClientAdmissionCrypto');
const vectors=require('../docs/human-client-admission/P256_CROSS_RUNTIME_TEST_VECTORS.json');
const {fixture}=require('./humanClientAdmissionFixtures');
const {TrustedClientAuthorityStore}=require('../modules/trustedClientAuthorityStore');
const N=BigInt('0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551');
const scalar=x=>Buffer.from(x.toString(16).padStart(64,'0'),'hex');
function normalize(raw){const s=BigInt('0x'+raw.subarray(32).toString('hex'));return Buffer.concat([raw.subarray(0,32),scalar(s>N/2n?N-s:s)]);}
function pfixture(){const h=fixture(),keys=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});const spki=keys.publicKey.export({type:'spki',format:'der'}).toString('base64url');const sign=p=>({nonceId:p.nonceId,signature:normalize(crypto.sign('sha256',Buffer.from(p.signingInput,'base64url'),{key:keys.privateKey,dsaEncoding:'ieee-p1363'})).toString('base64url')});const e=h.a.begin({protocolVersion:1,publicKeySpki:spki},'p256-fixture');h.a.browserDecision(e.enrollmentId,'approve');return {...h,keys,spki,sign,e};}
for(const v of vectors.cases)test('P256 vectors: '+v.name,()=>{
 let actual=false;try{const k=C.importPublicKey(Buffer.from(v.publicKeyDerHex,'hex').toString('base64url'));actual=C.verifyHumanClientProof({publicKeyAlgorithm:v.publicKeyAlgorithm,canonicalPublicKey:k.key,signingInput:Buffer.from(v.signingInputHex,'hex'),signature:Buffer.from(v.signatureHex,'hex').toString('base64url')});}catch{}
 assert.equal(actual,v.valid);if(v.boundFields)assert.equal(C.transcript(v.boundFields).bytes.toString('hex'),v.signingInputHex);
 assert.equal(crypto.createHash('sha256').update(Buffer.from(v.signingInputHex,'hex')).digest('hex'),v.sha256InputHex);
});
test('P256 lifecycle: all five proof purposes, durable recovery, gate and revoke match Ed25519 semantics',()=>{
 const h=pfixture(),s=h.a.claim(h.e.enrollmentId,h.sign(h.e.proof));assert.equal(h.store.get(s.clientEnrollmentId).publicKeyAlgorithm,'ECDSA_P256_SHA256');
 const n=h.a.nonce(s.sessionId,'capability-mint'),cap=h.a.mint(s.sessionId,h.sign(n));const ws=h.socket(),cl=h.authority.claimClientChannel(cap.capability),up=h.a.beginChannel(ws,cl);h.a.completeChannel(ws,h.sign(up));assert.equal(h.authority.isHuman(ws),false);assert.equal(h.a.client(s.clientEnrollmentId).productionAdmission,'DENIED');
 const other=fixture({storage:h.storage}),p=other.a.sessionChallenge(s.clientEnrollmentId),fresh=other.a.authenticate(s.clientEnrollmentId,h.sign(p));assert.equal(fresh.clientEnrollmentId,s.clientEnrollmentId);const revoke=other.a.nonce(fresh.sessionId,'self-revoke');other.a.selfRevoke(fresh.sessionId,h.sign(revoke));assert.equal(h.store.get(s.clientEnrollmentId).enrollmentState,'REVOKED');assert.throws(()=>h.a.nonce(s.sessionId,'capability-mint'));ws.close();
});
for(const field of ['algorithm','publicKeyAlgorithm'])test('P256 caller algorithm authority rejected: '+field,()=>{const h=fixture();assert.throws(()=>h.a.begin({protocolVersion:1,publicKeySpki:h.publicKeySpki,[field]:'ECDSA_P256_SHA256'},'caller'));});
for(const which of ['missing','unknown','substituted'])test('P256 registry algorithm fail closed: '+which,()=>{
 const h=pfixture(),s=h.a.claim(h.e.enrollmentId,h.sign(h.e.proof)),rp=path.join(h.storage.registryRoot,'authority.json'),ap=path.join(h.storage.anchorRoot,'anchor.json'),r=JSON.parse(fs.readFileSync(rp)),a=JSON.parse(fs.readFileSync(ap));
 if(which==='missing')delete r.clients[0].publicKeyAlgorithm;else r.clients[0].publicKeyAlgorithm=which==='unknown'?'unknown':'ED25519';a.authorityHeadCommitment=require('../modules/approvalReceiptAuthority').digest(r);fs.writeFileSync(rp,JSON.stringify(r));fs.writeFileSync(ap,JSON.stringify(a));assert.throws(()=>new TrustedClientAuthorityStore(h.storage),{code:'TRUSTED_CLIENT_RECOVERY_LOCKDOWN'});
});
test('P256 cross-enrollment key signatures and proof algorithm overrides reject',()=>{const p=pfixture(),ed=fixture(),e=ed.begin();ed.a.browserDecision(e.enrollmentId,'approve');assert.throws(()=>p.a.claim(p.e.enrollmentId,ed.sign(p.e.proof)));assert.throws(()=>ed.a.claim(e.enrollmentId,p.sign(e.proof)));assert.throws(()=>p.a.claim(p.e.enrollmentId,{...p.sign(p.e.proof),publicKeyAlgorithm:'ED25519'}));});
function derToP1363(b){if(b[0]!==0x30||b[1]!==b.length-2)throw Error('invalid DER');let i=2;const out=[];for(let n=0;n<2;n++){if(b[i++]!==2)throw Error('integer');const len=b[i++];let v=b.subarray(i,i+len);i+=len;if(!len||len>33||i>b.length||(v[0]&128)||(len>1&&v[0]===0&&!(v[1]&128)))throw Error('integer');if(v[0]===0)v=v.subarray(1);if(v.length>32)throw Error('integer');const n=BigInt('0x'+(v.toString('hex')||'0'));if(n<1n||n>=N)throw Error('scalar');out.push(Buffer.concat([Buffer.alloc(32-v.length),v]));}if(i!==b.length)throw Error('trailing');return Buffer.concat(out);}
test('P256 provider fixture: strict DER conversion and client low-S normalization',()=>{
 const f=vectors.providerFixtures,k=C.importPublicKey(Buffer.from(vectors.publicKeyDerHex,'hex').toString('base64url'));const verify=b=>C.verifyHumanClientProof({publicKeyAlgorithm:k.publicKeyAlgorithm,canonicalPublicKey:k.key,signingInput:Buffer.from(f.signingInputHex,'hex'),signature:b.toString('base64url')});const der=Buffer.from(f.providerDerHex,'hex');assert(!verify(der));assert.equal(normalize(derToP1363(der)).toString('hex'),f.convertedLowP1363Hex);assert(verify(Buffer.from(f.convertedLowP1363Hex,'hex')));const high=Buffer.from(f.providerHighSHex,'hex');assert(!verify(high));assert.equal(normalize(high).toString('hex'),f.normalizedLowP1363Hex);assert(verify(normalize(high)));assert(verify(Buffer.from(f.rawP1363Hex,'hex')));assert.throws(()=>derToP1363(Buffer.concat([der,Buffer.from([0])])));for(const bad of ['3006020100020101','300702020001020101','3006020180020101','3006020101020100'])assert.throws(()=>derToP1363(Buffer.from(bad,'hex')));
});
test('P256 base64url wire canonical encoding remains strict',()=>{const v=vectors.cases[0],k=C.importPublicKey(Buffer.from(v.publicKeyDerHex,'hex').toString('base64url')),s=Buffer.from(v.signatureHex,'hex').toString('base64url');for(const signature of [s+'=',s+'!',s.replace(/.$/,'/'),' '+s])assert(!C.verifyHumanClientProof({publicKeyAlgorithm:k.publicKeyAlgorithm,canonicalPublicKey:k.key,signingInput:Buffer.from(v.signingInputHex,'hex'),signature}));});
