'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../modules/humanClientAdmissionCrypto');
const vectors=require('../docs/human-client-admission/ED25519_CROSS_RUNTIME_TEST_VECTORS.json');
const pub=C.publicKey(vectors.publicKeySpki);assert.equal(pub.fingerprint,vectors.publicKeyFingerprint);
for(const v of vectors.cases)test('crypto_vectors: '+v.name,()=>{const t=C.transcript(v.boundFields);assert.equal(t.signingInput,v.signingInput);assert.equal(t.bytes.toString('hex'),v.signingInputHex);assert.equal(t.boundFieldDigest,v.boundFieldDigest);assert.equal(C.verify(pub.key,t.bytes,v.signature),v.valid);});
const weak=['00'.repeat(32),'01'+'00'.repeat(31),'26e8958fc2b227b045c3f489f2ef98f0d5dfac05d3c63339b13802886d53fc05','c7176a703d4dd84fba3c0b760d10670f2a2053fa2c39ccc64ec7fd7792ac037a','ec'+'ff'.repeat(30)+'7f','ed'+'ff'.repeat(30)+'7f','ee'+'ff'.repeat(30)+'7f'];
for(const [index,hex]of weak.entries())for(const sign of [0,128])test('crypto_weak_points: reject public weak encoding '+index+'/'+sign,()=>{const raw=Buffer.from(hex,'hex');raw[31]|=sign;const spki=Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),raw]).toString('base64url');assert.throws(()=>C.publicKey(spki),{code:'INVALID_ENROLLMENT'});});
test('crypto_weak_points: original OpenSSL identity forgery cannot enter enrollment',()=>{const crypto=require('node:crypto');const spki=Buffer.from('302a300506032b6570032100'+'01'+'00'.repeat(31),'hex');const key=crypto.createPublicKey({key:spki,type:'spki',format:'der'});const signature=Buffer.alloc(64);signature[0]=1;assert.equal(crypto.verify(null,Buffer.from('historical synthetic probe'),key,signature),true);const h=require('./humanClientAdmissionFixtures').fixture();assert.throws(()=>h.a.begin({protocolVersion:1,publicKeySpki:spki.toString('base64url')},'fixture'),{code:'INVALID_ENROLLMENT'});assert.equal(h.a.counts().enrollments,0);assert.equal(C.verify(pub.key,Buffer.from('probe'),signature.toString('base64url')),false);});
test('crypto_weak_points: noncanonical compressed coordinate is not admitted',()=>{const spki=Buffer.from('302a300506032b6570032100'+'ff'.repeat(32),'hex').toString('base64url');assert.throws(()=>C.publicKey(spki));});
