'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),http=require('node:http'),express=require('express');
const {once}=require('node:events');const WebSocket=require('ws');
process.env.HUMAN_CLIENT_HOST_ORIGIN='https://host.fixture';process.env.HUMAN_CLIENT_ADMIN_ORIGIN='https://admin.fixture';
const {authority}=require('../modules/approvalReceiptAuthority');const runtime=require('../modules/humanClientAdmissionRuntime');const fixtureHost=require('./humanClientAdmissionFixtures').fixture({authority,now:Date.now});runtime.getAdmission=()=>fixtureHost.a;const {getAdmission}=runtime;const bridge=require('../WebSocketServer');const {ApprovalProtocol}=require('../modules/approvalProtocol');const {ROOT,ADMIN,WS_PATH}=require('../modules/humanClientAdmission');const {createClientRouter,createAdminRouter}=require('../modules/humanClientAdmissionRoutes');const {env,auth}=require('./humanClientAdmissionFixtures');
function queue(ws){const values=[],waiters=[];ws.on('message',b=>{const x=JSON.parse(b);const i=waiters.findIndex(w=>w.type===x.type);if(i>=0){const w=waiters.splice(i,1)[0];clearTimeout(w.timer);w.resolve(x.data);}else values.push(x);});return type=>{const i=values.findIndex(x=>x.type===type);if(i>=0)return Promise.resolve(values.splice(i,1)[0].data);return new Promise((resolve,reject)=>{const w={type,resolve,timer:setTimeout(()=>{const i=waiters.indexOf(w);if(i>=0)waiters.splice(i,1);reject(Error('Missing '+type));},2000)};waiters.push(w);});};}
async function setup(t){const logs=[];t.mock.method(console,'log',(...a)=>logs.push(a.join(' ')));const a=getAdmission(),app=express();app.use('/human-client',createClientRouter());app.use(ADMIN,createAdminRouter({env}));const server=http.createServer(app);server.listen(0,'127.0.0.1');await once(server,'listening');const p=new ApprovalProtocol({authority,onTerminal:e=>bridge.broadcastApprovalTerminal(e)});bridge.setPluginManager({handleApprovalResponseOutcome:(d,s)=>p.respond(d,s),syncApprovals:s=>p.sync(s),cancelPendingApprovals:()=>p.cancelAll()});bridge.initialize(server,{vcpKey:'fixture-shared',debugMode:true,heartbeatEnabled:false});const origin='http://127.0.0.1:'+server.address().port;const clients=[];let session;
 t.after(async()=>{p.cancelAll();if(session)try{a.revoke(session.sessionId);}catch{}for(const s of clients)s.terminate();await bridge.shutdown();await new Promise(r=>server.close(r));});
 const keys=crypto.generateKeyPairSync('ed25519'),publicKeySpki=keys.publicKey.export({type:'spki',format:'der'}).toString('base64url');const sign=(proof,key=keys.privateKey)=>({nonceId:proof.nonceId,signature:crypto.sign(null,Buffer.from(proof.signingInput,'base64url'),key).toString('base64url')});
 const request=async(path,body,headers={})=>{const r=await fetch(origin+path,{method:body?'POST':'GET',headers:{...(body?{'content-type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});assert.equal(r.status<400,true,'isolated route accepted');return r;};
 const e=await(await request(ROOT+'/enrollments',{protocolVersion:1,publicKeySpki})).json();const page=await(await request(ADMIN+'/enrollments/'+e.enrollmentId,null,{authorization:auth})).text();const csrf=page.match(/name="csrf" value="([^"]+)"/)[1];await request(ADMIN+'/enrollments/'+e.enrollmentId+'/decision',{csrf,decision:'approve'},{authorization:auth,origin:'https://admin.fixture'});session=await(await request(ROOT+'/enrollments/'+e.enrollmentId+'/claim',sign(e.proof))).json();
 const cap=async()=>{const n=await(await request(ROOT+'/sessions/'+session.sessionId+'/nonces',{purpose:'capability-mint'})).json();return (await(await request(ROOT+'/sessions/'+session.sessionId+'/capability',sign(n))).json()).capability;};
 const connect=(token,path=WS_PATH)=>{const ws=new WebSocket(origin.replace('http:','ws:')+path,{headers:token?{'x-vcp-human-capability':token}:{}});clients.push(ws);const next=queue(ws);return {ws,next};};
 return {a,p,logs,session,sign,cap,connect,origin};}
test('websocket_routes: actual HTTP enrollment and channel proof remain TEST_ONLY, no production receipt',async t=>{const h=await setup(t),token=await h.cap(),{ws,next}=h.connect(token);const proof=await next('human_channel_challenge');assert.equal(proof.boundFields.path,WS_PATH);assert.equal(proof.boundFields.surface,'vcp_chat');assert.equal(proof.boundFields.capabilityDigest,crypto.createHash('sha256').update(token).digest('hex'));ws.send(JSON.stringify({type:'human_channel_proof',data:h.sign(proof)}));assert.equal((await next('human_channel_ready')).clientSurface,'vcp_chat');assert.equal(h.a.client(h.session.clientEnrollmentId).productionAdmission,'DENIED');const closed=once(ws,'close');ws.send(JSON.stringify({type:'tool_approval_sync',data:{protocolVersion:1}}));await closed;assert.equal(h.p.pendingCount,0);for(const secret of [token,proof.nonceId,h.sign(proof).signature])assert.equal(h.logs.some(x=>x.includes(secret)),false);});
for(const kind of ['capability-only','wrong-key','wrong-route','wrong-surface'])test('websocket_routes: '+kind+' never human',async t=>{const h=await setup(t),{ws,next}=h.connect(await h.cap()),proof=await next('human_channel_challenge');const closed=once(ws,'close');if(kind==='capability-only')ws.send(JSON.stringify({type:'tool_approval_sync',data:{protocolVersion:1}}));else{let response;if(kind==='wrong-key')response=h.sign(proof,crypto.generateKeyPairSync('ed25519').privateKey);else{const C=require('../modules/humanClientAdmissionCrypto');const fake=C.transcript({...proof.boundFields,...(kind==='wrong-route'?{path:'/VCPlog/admin-approval'}:{surface:'vcp_mobile'})});response=h.sign({...proof,signingInput:fake.signingInput});}ws.send(JSON.stringify({type:'human_channel_proof',data:response}));}await closed;assert.equal(h.p.pendingCount,0);});
test('websocket_routes: pending upgrade timeout closes without human authority', {timeout:15000},async t=>{const h=await setup(t),{ws,next}=h.connect(await h.cap());await next('human_channel_challenge');await once(ws,'close');assert.equal(h.a.counts().sockets,0);});
test('websocket_routes: reused cap and Mobile route rejected; generic route cannot upgrade',async t=>{const h=await setup(t),token=await h.cap(),first=h.connect(token);const proof=await first.next('human_channel_challenge');const repeated=h.connect(token);await once(repeated.ws,'error');const mobile=h.connect(await h.cap(),'/VCPlog/vcp-mobile-approval');await once(mobile.ws,'error');const g=h.connect(null,'/VCPlog/VCP_Key=fixture-shared');await g.next('connection_ack');g.ws.send(JSON.stringify({type:'human_channel_proof',data:h.sign(proof)}));g.ws.send(JSON.stringify({type:'tool_approval_sync',data:{protocolVersion:1}}));assert.equal((await g.next('tool_approval_snapshot')).outcome,'CLIENT_NOT_AUTHORIZED');assert.equal(h.logs.some(x=>x.includes(h.sign(proof).signature)),false,'generic PoP attempts must not log signatures');first.ws.send(JSON.stringify({type:'human_channel_proof',data:h.sign(proof)}));await first.next('human_channel_ready');const close=once(first.ws,'close');first.ws.send(JSON.stringify({type:'human_channel_proof',data:h.sign(proof)}));await close;});
